WITH DILA AS (
    SELECT
        ILPINN,
        ILSPCD,
        SUM(ILINVP * ILQTYI) AS ITEMTOTAL,
        MAX(ILPORD) AS PONUM
    FROM DILL02
    WHERE ILDOFD > {{ date_min }}
    GROUP BY ILPINN, ILSPCD
)
SELECT 
    DIH.IHINVD,
    CASE 
        WHEN TRIM(DSH.SHTPTC) = '' THEN '50'
        ELSE DSH.SHTPTC
    END AS SHTPTC,
    DIH.IHSHPN,
    DIH.IHSPCD,
    DIH.IHPRCC,
    DIH.IHPRCT,
    DILA.ITEMTOTAL,
    TRIM(DPO.POWHCD) AS WAREHOUSE,
    DPKT.GROSSWEIGHT,
    (DIH.IHPRCT - DILA.ITEMTOTAL) AS FREIGHT_CHARGE
FROM DIHL02 DIH
INNER JOIN DILA
    ON DIH.IHPINN = DILA.ILPINN AND DIH.IHSPCD = DILA.ILSPCD
INNER JOIN (
    SELECT
        PKSPCD,
        PKSHPN,
        SUM(PKPKGW) AS GROSSWEIGHT
    FROM DPKL02
    GROUP BY PKSPCD, PKSHPN
) DPKT
    ON DIH.IHSHPN = DPKT.PKSHPN AND DIH.IHSPCD = DPKT.PKSPCD
INNER JOIN DSHL02 DSH
    ON DIH.IHSHPN = DSH.SHSHPN AND DIH.IHSPCD = DSH.SHSPCD
INNER JOIN DPOL02 DPO
    ON DILA.PONUM = DPO.POPORD
WHERE DIH.IHDOFD >  {{ date_min }}
{% if warehouses %}
  AND TRIM(DPO.POWHCD) IN (
    {% for warehouse in warehouses %}
      '{{ warehouse }}'{% if not loop.last %}, {% endif %}
    {% endfor %}
  )
{% endif %}