SELECT 
    TRIM(DPS.PSPITM) AS ITEMNUM_PARENT,
    TRIM(DPS.PSCITM) AS ITEMNUM_CHILD,
    DPS.PSCQTY,DPS.PSSTRF AS TYPE,
    DPS.PSUSES AS USING_EXISTING 
FROM DPSL01 DPS
INNER JOIN IIML01 IIM1 ON DPS.PSCITM = IIM1.IPROD 
INNER JOIN IIML01 IIM2 ON DPS.PSPITM = IIM2.IPROD
WHERE DPS.PSSTRF = '1'
    AND DPS.PSCITM NOT LIKE '97%'
    AND DPS.PSPITM NOT LIKE '97%'